### PR TITLE
Update bot to work with Python 3.5+

### PR DESCRIPTION
**Pull request by JSchwerberg**
## Short Description:

Update bot to work with both Python 2.7+ and Python 3.5+
## Fixes/Resolves/Closes (please use correct syntax):

N/A

### CODE REVIEW

**Review by javajohnHub — COMMENTED** [review]
I have been running this for over an hour with no issues encountered.

**Comment by javajohnHub** [comment]
2 hours now. No issues.

**Comment by Gobberwart** [comment]
Running on Py2.7 without issues so far.

**Comment by JSchwerberg** [comment]
Closing issue to re-apply to real repo.

**Pull request closed without merging**
